version: '3.8'

services:
  # Pegasus Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Backend connection - uses host.docker.internal to reach host machine from container
      - BACKEND_URL=http://host.docker.internal:3001
      - NEXT_PUBLIC_API_BASE_URL=http://host.docker.internal:3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
