version: '3.8'

services:
  # Next.js frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Connect to your existing backend on port 3001
      - NEXT_PUBLIC_API_BASE_URL=http://37.114.41.124:3001
    restart: unless-stopped
    network_mode: "host"  # Use host network to connect to existing backend

# Optional: Add volumes for persistent data
volumes:
  frontend-data:
    driver: local
