version: '3.8'

services:
  # Your Next.js frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - pegasus-network

networks:
  pegasus-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  app-data:
    driver: local
