version: '3.8'

services:  # Backend service - using a placeholder image for now
  # Remove this service if you have a separate backend deployment
  backend:
    image: nginx:alpine
    container_name: pegasus-backend
    ports:
      - "3000:80"
    volumes:
      - ./backend-placeholder.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pegasus-network
    # This is a placeholder - replace with your actual backend service
      # Your Next.js frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pegasus-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Backend API URL for internal communication
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - pegasus-network
    restart: unless-stopped

networks:
  pegasus-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  mongo-data:
    driver: local
